name: FitnessApp CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu Klonla
      uses: actions/checkout@v4

    - name: .NET 9 Kurulumu
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Bağımlılıkları Yükle (Restore)
      run: dotnet restore

    - name: Projeyi Derle (Build)
      run: dotnet build --configuration Release --no-restore

    - name: Birim Testlerini Çalıştır (Test)
      run: dotnet test --configuration Release --no-build --verbosity normal